version: 2

registries:
  github-packages:
    type: rubygems-server
    url: https://rubygems.pkg.github.com
    token: ${{secrets.MY_GITHUB_TOKEN}}

updates:
  - package-ecosystem: 'docker'
    directory: '/Docker/api'
    schedule:
      interval: 'daily'
      time: '03:00'
      timezone: 'Asia/Tokyo'
    commit-message:
      prefix: 'build'
    target-branch: 'main'
  - package-ecosystem: 'docker'
    directory: '/Docker/db'
    schedule:
      interval: 'daily'
      time: '03:00'
      timezone: 'Asia/Tokyo'
    commit-message:
      prefix: 'build'
    target-branch: 'main'
  - package-ecosystem: 'docker'
    directory: '/Docker/web'
    schedule:
      interval: 'daily'
      time: '03:00'
      timezone: 'Asia/Tokyo'
    commit-message:
      prefix: 'build'
    target-branch: 'main'
  - package-ecosystem: 'bundler'
    registries:
      - github-packages
    directory: '/'
    schedule:
      interval: 'daily'
      time: '03:00'
      timezone: 'Asia/Tokyo'
    commit-message:
      prefix: 'build'
    target-branch: 'main'


